# backend/api/auth_routes.py
from fastapi import APIRouter, Depends, HTTPException, status
from fastapi.security import OAuth2PasswordRequestForm
from sqlalchemy.orm import Session
from database import get_db
from models import db_models, schemas
from auth_utils import get_password_hash, verify_password, create_access_token, get_current_user
from typing import List

router = APIRouter()

@router.post("/register", response_model=schemas.UserResponse)
def register_user(user: schemas.UserCreate, db: Session = Depends(get_db)):
    # 1. THE PROFESSIONAL FIX: Normalize the email (lowercase & remove accidental spaces)
    clean_email = user.email.strip().lower()

    # Check if user already exists using the clean email
    db_user = db.query(db_models.User).filter(db_models.User.email == clean_email).first()
    if db_user:
        raise HTTPException(status_code=400, detail="Email already registered")
    
    # Create new user saving ONLY the clean email
    hashed_password = get_password_hash(user.password)
    new_user = db_models.User(email=clean_email, hashed_password=hashed_password)
    
    db.add(new_user)
    db.commit()
    db.refresh(new_user)
    return new_user


@router.post("/login", response_model=schemas.Token)
def login(form_data: OAuth2PasswordRequestForm = Depends(), db: Session = Depends(get_db)):
    # 1. THE PROFESSIONAL FIX: Normalize the incoming login attempt
    clean_email = form_data.username.strip().lower()

    # Look up the user using the clean email
    user = db.query(db_models.User).filter(db_models.User.email == clean_email).first()
    
    if not user or not verify_password(form_data.password, user.hashed_password):
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Incorrect email or password",
            headers={"WWW-Authenticate": "Bearer"},
        )
    
    access_token = create_access_token(data={"sub": user.email})
    return {"access_token": access_token, "token_type": "bearer"}

@router.get("/me", response_model=schemas.UserResponse)
def get_user_profile(current_user: db_models.User = Depends(get_current_user)):
    # This is a protected route. It requires a valid JWT token to access.
    return current_user

@router.put("/me/settings", response_model=schemas.UserResponse)
def update_user_settings(
    settings: schemas.UserUpdateSettings, 
    db: Session = Depends(get_db), 
    current_user: db_models.User = Depends(get_current_user)
):
    """Securely stores the user's personal API keys and brand voice in the DB"""
    
    # Only update fields that were actually sent in the request
    if settings.gemini_key is not None:
        current_user.gemini_key = settings.gemini_key
    if settings.devto_key is not None:
        current_user.devto_key = settings.devto_key
    if settings.hashnode_token is not None:
        current_user.hashnode_token = settings.hashnode_token
    if settings.hashnode_pub_id is not None:
        current_user.hashnode_pub_id = settings.hashnode_pub_id
    if settings.brand_voice is not None:
        current_user.brand_voice = settings.brand_voice

    db.commit()
    db.refresh(current_user)
    return current_user

@router.get("/me/history", response_model=List[schemas.WorkspaceResponse])
def get_user_history(
    db: Session = Depends(get_db), 
    current_user: db_models.User = Depends(get_current_user)
):
    """Fetches all workspaces generated by the logged-in user, most recently edited first"""
    
    workspaces = db.query(db_models.Workspace)\
        .filter(db_models.Workspace.user_id == current_user.id)\
        .order_by(db_models.Workspace.last_edited.desc())\
        .all()
        
    return workspaces